In [11]:
max_len = 23
from tensorflow import keras
from transformers import TFBertModel, BertTokenizer

# Load BERT model and tokenizer
bert_model = TFBertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Define multi-head model
class MultiHeadNER(keras.Model):
  def __init__(self, num_heads=3):
    super().__init__()
    self.bert = bert_model
    self.head_1 = keras.layers.Dense(3, activation='softmax')  # 3 for each entity type
    self.head_2 = keras.layers.Dense(3, activation='softmax')
    self.head_3 = keras.layers.Dense(3, activation='softmax')

  def call(self, inputs):
    bert_outputs = self.bert(inputs[0], attention_mask=inputs[1])
    outputs = [
        self.head_1(bert_outputs[0]),
        self.head_2(bert_outputs[0]),
        self.head_3(bert_outputs[0])
    ]
    return outputs

# Create model instance
model = MultiHeadNER()

# Define loss functions and metrics (example)
loss_fn = [
    keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    keras.losses.SparseCategoricalCrossentropy(from_logits=True)
]
metrics = [
    keras.metrics.SparseCategoricalAccuracy(),
    keras.metrics.SparseCategoricalAccuracy(),
    keras.metrics.SparseCategoricalAccuracy()
]

# Compile and train your model (replace with your training data)
model = MultiHeadNER()
model.build(input_shape=[(None, max_len), (None, max_len)])
model.compile(optimizer='adam', loss=loss_fn, metrics=metrics)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

ValueError: You cannot build your model by calling `build` if your layers do not support float type inputs. Instead, in order to instantiate and build your model, call your model on real tensor data (of the correct dtype).

The actual error from `call` is: Exception encountered when calling layer 'tf_bert_model_4' (type TFBertModel).

in user code:

    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 1208, in run_call_with_unpacked_inputs  *
        return func(self, **unpacked_inputs)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/transformers/models/bert/modeling_tf_bert.py", line 1235, in call  *
        outputs = self.bert(
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_file2bfp_1ax.py", line 37, in tf__run_call_with_unpacked_inputs
        retval_ = ag__.converted_call(ag__.ld(func), (ag__.ld(self),), dict(**ag__.ld(unpacked_inputs)), fscope)
    File "/tmp/__autograph_generated_filep77lfuan.py", line 127, in tf__call
        embedding_output = ag__.converted_call(ag__.ld(self).embeddings, (), dict(input_ids=ag__.ld(input_ids), position_ids=ag__.ld(position_ids), token_type_ids=ag__.ld(token_type_ids), inputs_embeds=ag__.ld(inputs_embeds), past_key_values_length=ag__.ld(past_key_values_length), training=ag__.ld(training)), fscope)
    File "/tmp/__autograph_generated_fileakf1myg1.py", line 46, in tf__call
        ag__.if_stmt(ag__.ld(input_ids) is not None, if_body_1, else_body_1, get_state_1, set_state_1, ('inputs_embeds',), 1)
    File "/tmp/__autograph_generated_fileakf1myg1.py", line 41, in if_body_1
        inputs_embeds = ag__.converted_call(ag__.ld(tf).gather, (), dict(params=ag__.ld(self).weight, indices=ag__.ld(input_ids)), fscope)

    TypeError: Exception encountered when calling layer 'bert' (type TFBertMainLayer).
    
    in user code:
    
        File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 1208, in run_call_with_unpacked_inputs  *
            return func(self, **unpacked_inputs)
        File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/transformers/models/bert/modeling_tf_bert.py", line 913, in call  *
            embedding_output = self.embeddings(
        File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "/tmp/__autograph_generated_fileakf1myg1.py", line 46, in tf__call
            ag__.if_stmt(ag__.ld(input_ids) is not None, if_body_1, else_body_1, get_state_1, set_state_1, ('inputs_embeds',), 1)
        File "/tmp/__autograph_generated_fileakf1myg1.py", line 41, in if_body_1
            inputs_embeds = ag__.converted_call(ag__.ld(tf).gather, (), dict(params=ag__.ld(self).weight, indices=ag__.ld(input_ids)), fscope)
    
        TypeError: Exception encountered when calling layer 'embeddings' (type TFBertEmbeddings).
        
        in user code:
        
            File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/transformers/models/bert/modeling_tf_bert.py", line 208, in call  *
                inputs_embeds = tf.gather(params=self.weight, indices=input_ids)
        
            TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64
        
        
        Call arguments received by layer 'embeddings' (type TFBertEmbeddings):
          • input_ids=tf.Tensor(shape=(None, 23), dtype=float32)
          • position_ids=None
          • token_type_ids=tf.Tensor(shape=(None, 23), dtype=int32)
          • inputs_embeds=None
          • past_key_values_length=0
          • training=False
    
    
    Call arguments received by layer 'bert' (type TFBertMainLayer):
      • input_ids=tf.Tensor(shape=(None, 23), dtype=float32)
      • attention_mask=tf.Tensor(shape=(None, 23), dtype=float32)
      • token_type_ids=None
      • position_ids=None
      • head_mask=None
      • inputs_embeds=None
      • encoder_hidden_states=None
      • encoder_attention_mask=None
      • past_key_values=None
      • use_cache=True
      • output_attentions=False
      • output_hidden_states=False
      • return_dict=True
      • training=False


Call arguments received by layer 'tf_bert_model_4' (type TFBertModel):
  • input_ids=tf.Tensor(shape=(None, 23), dtype=float32)
  • attention_mask=tf.Tensor(shape=(None, 23), dtype=float32)
  • token_type_ids=None
  • position_ids=None
  • head_mask=None
  • inputs_embeds=None
  • encoder_hidden_states=None
  • encoder_attention_mask=None
  • past_key_values=None
  • use_cache=None
  • output_attentions=None
  • output_hidden_states=None
  • return_dict=None
  • training=False.

O
O
B-task_detail
I-task_detail
I-task_detail
O
O
O
O


In [39]:
import tensorflow as tf
# Select a single input case from your dataset

input_statement = "schedule a meeting with john tomorrow at 2 pm"
task_index = ['O', 'O', 'B-task_detail', 'I-task_detail', 'I-task_detail', 'O', 'O', 'O', 'O']
date_index = ['O', 'O', 'O', 'O', 'O', 'B-date', 'O', 'O', 'O']
time_index = ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-time', 'I-time']

# Tokenize the input statement using the BERT tokenizer
inputs = tokenizer(input_statement, add_special_tokens=True, padding='max_length', truncation=True, max_length=25, return_tensors="tf")

# Encode labels for the input case
label_to_index = {"O": 0, "B-task_detail": 1, "I-task_detail": 2, "B-date": 3, "I-date": 4, "B-time": 5, "I-time": 6}
encoded_labels_task = [label_to_index[label] for label in task_index]
encoded_labels_date = [label_to_index[label] for label in date_index]
encoded_labels_time = [label_to_index[label] for label in time_index]


# Pad labels with "O" to make them rectangular
max_length = 25
padded_labels_task = encoded_labels_task + [0] * (max_length - len(encoded_labels_task))
padded_labels_date = encoded_labels_date + [0] * (max_length - len(encoded_labels_date))
padded_labels_time = encoded_labels_time + [0] * (max_length - len(encoded_labels_time))

# Convert padded labels to TensorFlow tensors
padded_labels_task = tf.constant([padded_labels_task])
padded_labels_date = tf.constant([padded_labels_date])
padded_labels_time = tf.constant([padded_labels_time])

# Perform training or inference using the model and the single input case
# Example:
# predictions = model(inputs)
# loss = calculate_loss(predictions, [encoded_labels_task, encoded_labels_date, encoded_labels_time])
# Perform backpropagation and update model parameters for training
# Update this part based on your specific training/inference process



In [41]:
padded_labels_date

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]], dtype=int32)>

In [48]:
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer

# Load pre-trained BERT model and tokenizer
bert_model_name = "bert-base-uncased"
bert_tokenizer = BertTokenizer.from_pretrained(bert_model_name)
bert_model = TFBertModel.from_pretrained(bert_model_name)

# Define input layers
input_ids = tf.keras.layers.Input(shape=(None,), dtype=tf.int32, name="input_ids")

# Get BERT outputs
bert_outputs = bert_model(input_ids)[0]  # Output from BERT's last layer

# Define classification heads for each entity type
num_labels_task = 3  # "O", "B-task", "I-task"
num_labels_date = 3  # "O", "B-date", "I-date"
num_labels_time = 3  # "O", "B-time", "I-time"
dropout_rate = 0.1

# Task classification head
task_logits = tf.keras.layers.Dense(num_labels_task, activation=None, name="task_logits")(bert_outputs)
task_output = tf.keras.layers.Activation("softmax", name="task_output")(task_logits)

# Date classification head
date_logits = tf.keras.layers.Dense(num_labels_date, activation=None, name="date_logits")(bert_outputs)
date_output = tf.keras.layers.Activation("softmax", name="date_output")(date_logits)

# Time classification head
time_logits = tf.keras.layers.Dense(num_labels_time, activation=None, name="time_logits")(bert_outputs)
time_output = tf.keras.layers.Activation("softmax", name="time_output")(time_logits)

# Define the model
model = tf.keras.Model(inputs=input_ids, outputs=[task_output, date_output, time_output])
# model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Define separate loss functions for each entity type
loss_function_task = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_function_date = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_function_time = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Compile the model with multiple metrics
model.compile(optimizer='adam',
              loss={'task_output': loss_function_task,
                    'date_output': loss_function_date,
                    'time_output': loss_function_time},
              metrics={'task_output': 'accuracy',
                       'date_output': 'accuracy',
                       'time_output': 'accuracy'})

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [42]:
print(len(inputs['input_ids']), len(padded_labels_task), len(padded_labels_date), len(padded_labels_time))

1 1 1 1


In [43]:
padded_labels_date

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]], dtype=int32)>

In [58]:
from transformers import TFBertModel
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.models import Model

# Define the inputs
input_ids = Input(shape=(None,), dtype=tf.int32, name='input_ids')

# Load the base BERT model
bert = TFBertModel.from_pretrained('bert-base-cased')

# Connect the inputs to the BERT model
bert_output = bert(input_ids)

# Add dropout for regularization
dropout = Dropout(bert.config.hidden_dropout_prob)(bert_output[0])

# Add a separate dense layer for each task
task_head = Dense(3, activation='softmax', name='task_output')(dropout)
date_head = Dense(3, activation='softmax', name='date_output')(dropout)
time_head = Dense(3, activation='softmax', name='time_output')(dropout)

# Combine it all into a Model
model = Model(inputs=input_ids, outputs=[task_head, date_head, time_head])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5), 
              loss={'task_output': tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
                    'date_output': tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
                    'time_output': tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)}, 
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [59]:
model.fit(
    inputs['input_ids'],
    {'task_output': padded_labels_task, 'date_output': padded_labels_date, 'time_output': padded_labels_time},
    epochs=5
)

Epoch 1/5


ValueError: in user code:

    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/engine/compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/losses.py", line 2221, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/home/adit/anaconda3/envs/tf/lib/python3.10/site-packages/keras/src/backend.py", line 5573, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 25) and (None, 25, 3) are incompatible
